#! /bin/sh

unfocused=#3a3a3a
focused=#85add4

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           0
bspc config top_padding          33 # Polybar height needed for toggle script

bspc config normal_border_color			$unfocused
bspc config active_border_color			$unfocused
bspc config focused_border_color		$focused

bspc config automatic_scheme		    alternate

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle			true

bspc config focus_follows_pointer		true

bspc config external_rules_command "$(which ~/.config/bspwm/external-rules.sh)"

bspc rule -a Thunderbird desktop='^3' follow=on
bspc rule -a Mailspring desktop='^3' follow=on
bspc rule -a Filezilla   desktop='^4'
bspc rule -a firefox desktop='^2'

bspc desktop ^2 -l monocle
bspc desktop ^1 -l monocle

$HOME/.config/polybar/launch.sh
$HOME/.config/flameshot/launch.sh
